dist: eoan
warnings_are_errors: false
language: r
r:
  - release
cache:
  - packages
  - ccache
r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr); codecov()'

addons:
  apt:
    sources:
      - sourceline: ppa:ubuntugis/ubuntugis-unstable
    packages:
      - libudunits2-dev
      - libgdal-dev
      - libgeos-dev
      - libproj-dev
      - liblwgeom-dev

before_install:
  - R -q -e 'install.packages("devtools"); devtools::install_github("r-spatial/lwgeom")'

# safelist
branches:
  only:
  - master
  - devbranch
