dist: bionic
warnings_are_errors: false
language: r
r:
  - release
cache:
  - packages
  - ccache
r_packages:
  - covr
r_github_packages:
  - jimhester/lintr
after_success:
  - Rscript -e 'library(covr); codecov()'
  - R CMD INSTALL $PKG_TARBALL
  - Rscript -e 'lintr::lint_package()'

addons:
  apt:
    sources:
      - sourceline: ppa:ubuntugis/ubuntugis-unstable
    packages:
      - libudunits2-dev
      - libproj-dev
      - libgdal-dev
      - libgeos-dev
      - liblwgeom-dev

before_install:
  - sudo apt-get install pkg-config
  - R -q -e 'install.packages("devtools"); devtools::install_github("r-spatial/lwgeom")'

# safelist
branches:
  only:
  - master
  - develop
