warnings_are_errors: false
language: r
r:
  - release
cache: packages
r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr); codecov()'

addons:
  apt:
    sources:
      - sourceline: ppa:ubuntugis/ubuntugis-unstable
    packages:
      - libudunits2-dev
      - libgdal-dev
      - libgeos-dev
      - libproj-dev
      - libfontconfig1-dev
      - r-cran-lwgeom

# safelist
branches:
  only:
  - master
  - devbranch
