language: r
r:
  - release

addons:
  apt:
    sources:
      - sourceline: ppa:ubuntugis/ubuntugis-unstable
    packages:
      - libudunits2-dev
      - libgdal-dev
      - libgeos-dev
      - libproj-dev

# safelist
branches:
  only:
  - master

environment:
  global:
    WARNINGS_ARE_ERORRS: 0
