warnings_are_errors: false
CODECOV_TOKEN="b029e2a4-d34f-4717-9830-28d32f86ee43"
language: r
r:
  - release
r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr); codecov()'

addons:
  apt:
    sources:
      - sourceline: ppa:ubuntugis/ubuntugis-unstable
    packages:
      - libudunits2-dev
      - libgdal-dev
      - libgeos-dev
      - libproj-dev

# safelist
branches:
  only:
  - master
